#===================================================================#
#   Regional Plot for Menopause GWAS and QTLs (DHX58)
#   This script reads the SMR plot data and generates a PDF.
#===================================================================#

# Load required library and source the plotting function
# Ensure the path to plot_epiSMR.r is correct
source("/path/to/plot_SMR.r")   # Update this path

# ------------------------------ #
#   Define input and output files
# ------------------------------ #
probe_id <- "ENSG00000108771"
plot_data_file <- paste0("menopause_", probe_id, ".txt")   # Generated by SMR --plot
output_pdf <- paste0("menopause_", probe_id, ".pdf")

# ------------------------------ #
#   Read SMR plot data
# ------------------------------ #
plotdata <- ReadSMRData(plot_data_file)

# ------------------------------ #
#   Parameters for plotting
# ------------------------------ #
window_kb <- 350                    # Plot window in kb around the top SNP
smr_thresh <- 1e-4                  # SMR significance threshold
heidi_thresh <- 0.01                 # HEIDI test threshold
trait_name <- "Age at menopause"     # GWAS trait name
center_bp <- 40134782                 # Center position (in bp) for the plot

# List of probe names to highlight (must match names in plotdata)
probes_to_show <- c(
    "pQTL_14012_17_LGP2",
    "eQTL_ENSG00000108771",
    "sQTL_ENSG00000108771.13"
)

# ------------------------------ #
#   Generate the plot
# ------------------------------ #
pdf(output_pdf, height = 8, width = 6)

SMRLocusPlot(
    data = plotdata,
    probeNEARBY = probes_to_show,
    smr_thresh = smr_thresh,
    smr_thresh_plot = smr_thresh,
    heidi_thresh = heidi_thresh,
    heidi_thresh_plot = heidi_thresh,
    plotWindow = window_kb,
    trait_name = trait_name,
    pointsize = 20,
    max_anno_probe = 2,
    epi_plot = FALSE,
    anno_self = TRUE,
    plotBP = center_bp,
    annoSig_only = FALSE
)

dev.off()

message("Plot saved as: ", output_pdf)